name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Transfer repository to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        source: "./"
        target: "/home/${{ secrets.USERNAME }}/eth-faucet"

    - name: Transfer TLS certificate to the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          mkdir /home/${{ secrets.USERNAME }}/eth-faucet/certs
          echo "${{ secrets.CERT_PRIVATE_KEY }}" > /home/${{ secrets.USERNAME }}/eth-faucet/certs/privkey.pem
          echo "${{ secrets.CERT_FULL_CHAIN }}" > /home/${{ secrets.USERNAME }}/eth-faucet/certs/fullchain.pem
        
    - name: Transfer config to the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          echo '${{ secrets.CONFIG }}' > /home/${{ secrets.USERNAME }}/eth-faucet/config.js

    - name: Install dependencies
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          sudo apt-get update
          sudo apt-get install docker-compose

    - name: Run docker compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd eth-faucet
          sudo docker-compose build --no-cache
          sudo docker-compose up -d --force-recreate --remove-orphans